---
##########################
## Hadolint config file ##
##########################
ignored:

override:
  info:
    - DL3006 # Always tag the version specifically
    - DL3007 # Latest tag warning
failure-threshold: warning