---
name: Docker
on:
  push:
    branches: [master, workflow-test]
  pull_request:
    branches: [master, workflow-test]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          # Docker images to use as base name for tags
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/tagbot
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref, event=tag
            type=semver,pattern={{raw}}
          flavor: latest=true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tagbot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/tagbot:buildcache,mode=max
      -
        name: Show image digest
        run: echo ${{ steps.build.outputs.digest }}