---
name: Docker
on:
  push:
    branches: [master, workflow-test]
  pull_request:
    branches: [master, workflow-test]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Tag
        id: tag
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
          search_commit_body: true

        # name: Docker metadata
        # id: meta
        # uses: docker/metadata-action@v3.6.2
        # with:
        #   # Docker images to use as base name for tags
        #   images: ${{ secrets.DOCKER_HUB_USERNAME }}/tagbot
        #   # generate Docker tags based on the following events/attributes
        #   tags: |
        #     type=ref, event=tag
        #     type=semver,pattern={{raw}}
        #   flavor: latest=true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
              orionhumphrey/tagbot:${{ steps.tag.outputs.version_tag }}
              orionhumphrey/tagbot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
